#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;
using Debug = UnityEngine.Debug;

/// <summary>
/// Detects and fixes CocoaPods version conflicts in the Podfile generated by EDM4U, during the
/// iOS build, before EDM4U / CI run `pod install`.
///
/// How it works (loop, max <see cref="MaxAttempts"/> passes):
///   1. Run `pod install` in the exported Xcode project.
///   2. Success -> done.
///   3. "could not find compatible versions for pod X" -> parse who wants what:
///        - X is declared directly in the Podfile (from some *Dependencies.xml) AND another pod
///          depends on a different X version (e.g. a mediation adapter pinning its network SDK):
///          drop the direct constraint so the dependent pod decides, then retry.
///        - Only transitive pods disagree (two adapters want different X): can't be fixed safely.
///          Fail the build with a report naming the pods and the XML files that declare them.
///   4. Stale Podfile.lock in the conflict -> delete it and retry.
///      Out-of-date spec repo -> retry once with --repo-update.
///      Higher minimum deployment target -> fail with a clear message (needs a Player Settings decision).
///   5. Anything else -> fail the build with the tail of the pod output.
///
/// Order: EDM4U generates the Podfile at 40 (IOSResolver.BUILD_ORDER_GEN_PODFILE) and runs
/// `pod install` at 50 (BUILD_ORDER_INSTALL_PODS). Unity sorts IPostprocessBuildWithReport
/// callbacks and [PostProcessBuild] attributes together, so 45 runs in between. Literal used so
/// this package needs no reference to Google.IOSResolver.dll.
///
/// Optional config: ProjectSettings/PodfileOverrides.json
/// {
///   "disableAutoResolve": false,
///   "overrides": [ { "pod": "Some-SDK", "version": "1.2.3" } ]
/// }
/// Overrides are applied first. A pod pinned with a non-empty version is never touched by the
/// auto-resolver; if it still conflicts, the build fails and tells you. "version": "" drops the constraint.
/// </summary>
public class CocoaPodsConflictResolver : IPostprocessBuildWithReport
{
    public const string ConfigPath = "ProjectSettings/PodfileOverrides.json";
    private const int MaxAttempts = 8;
    private const int PodTimeoutMinutes = 20;
    private const string Tag = "[PodResolver]";

    public int callbackOrder => 45;

    // ------------------------------------------------------------------ config

    [Serializable]
    private class PodOverride
    {
        public string pod;
        public string version; // "" = drop the constraint
    }

    [Serializable]
    private class Config
    {
        public bool disableAutoResolve;
        public List<PodOverride> overrides = new List<PodOverride>();

        public bool IsPinned(string pod) =>
            overrides != null && overrides.Any(o => o.pod == pod && !string.IsNullOrWhiteSpace(o.version));
    }

    private static Config LoadConfig()
    {
        if (!File.Exists(ConfigPath))
            return new Config();

        try
        {
            return JsonUtility.FromJson<Config>(File.ReadAllText(ConfigPath)) ?? new Config();
        }
        catch (Exception e)
        {
            throw new BuildFailedException($"{Tag} Invalid {ConfigPath}: {e.Message}");
        }
    }

    // ------------------------------------------------------------------ entry

    public void OnPostprocessBuild(BuildReport report)
    {
        if (report.summary.platform != BuildTarget.iOS)
            return;

        string projectDir = report.summary.outputPath;
        string podfilePath = Path.Combine(projectDir, "Podfile");
        if (!File.Exists(podfilePath))
        {
            Debug.LogWarning($"{Tag} No Podfile at {podfilePath} (EDM4U Podfile generation disabled?). Skipping.");
            return;
        }

        Config config = LoadConfig();

        foreach (PodOverride o in config.overrides ?? new List<PodOverride>())
        {
            if (!string.IsNullOrWhiteSpace(o.pod))
                SetPodVersion(podfilePath, o.pod.Trim(), o.version, "manual override");
        }

        if (config.disableAutoResolve)
            return;

        if (Application.platform != RuntimePlatform.OSXEditor)
        {
            Debug.LogWarning($"{Tag} CocoaPods only runs on macOS; conflict check skipped on this machine.");
            return;
        }

        Resolve(projectDir, podfilePath, config);
    }

    // ------------------------------------------------------------------ resolve loop

    private static void Resolve(string projectDir, string podfilePath, Config config)
    {
        var fixes = new List<string>();
        var relaxed = new HashSet<string>();
        bool repoUpdated = false;
        bool lockDeleted = false;
        string args = "install";

        for (int attempt = 1; attempt <= MaxAttempts; attempt++)
        {
            Debug.Log($"{Tag} pod {args} (pass {attempt}/{MaxAttempts})");
            (int exitCode, string output) = RunPod(projectDir, args);
            args = "install";

            if (exitCode == 0)
            {
                Debug.Log(fixes.Count == 0
                    ? $"{Tag} pod install OK, no conflicts."
                    : $"{Tag} pod install OK after {fixes.Count} fix(es):\n  - " + string.Join("\n  - ", fixes) +
                      "\nFix the source XML / update the plugin when convenient; check the native bridge still compiles.");
                return;
            }

            PodConflict conflict = PodConflict.Parse(output);
            if (conflict != null)
            {
                // Stale lock file from an earlier build into the same folder.
                if (conflict.FromLockfile && !lockDeleted)
                {
                    string lockPath = Path.Combine(projectDir, "Podfile.lock");
                    if (File.Exists(lockPath)) File.Delete(lockPath);
                    lockDeleted = true;
                    fixes.Add($"deleted stale Podfile.lock (conflict on {conflict.Pod})");
                    continue;
                }

                bool fixable = conflict.Direct.Count > 0
                               && conflict.Transitive.Count > 0
                               && conflict.Transitive.Select(t => t.Requirement).Distinct().Count() == 1
                               && !config.IsPinned(conflict.Pod)
                               && !relaxed.Contains(conflict.Pod);

                if (fixable)
                {
                    PodRequirement winner = conflict.Transitive[0];
                    SetPodVersion(podfilePath, conflict.Pod, "", "conflict");
                    relaxed.Add(conflict.Pod);
                    fixes.Add($"{conflict.Pod}: dropped '{string.Join(", ", conflict.Direct)}' " +
                              $"(declared in {DescribeSources(conflict.Pod)}); " +
                              $"now governed by {winner.Via} ({winner.Requirement})");
                    continue;
                }

                throw new BuildFailedException(conflict.Describe(config.IsPinned(conflict.Pod)));
            }

            if (!repoUpdated && (output.Contains("pod repo update") ||
                                 output.Contains("None of your spec sources contain a spec satisfying")))
            {
                repoUpdated = true;
                args = "install --repo-update";
                continue;
            }

            Match deploy = Regex.Match(output,
                @"Specs satisfying the `(?<dep>[^`]+)` dependency were found, but they required a higher minimum deployment target");
            if (deploy.Success)
            {
                throw new BuildFailedException(
                    $"{Tag} '{deploy.Groups["dep"].Value}' needs a higher iOS deployment target than " +
                    $"{PlayerSettings.iOS.targetOSVersionString} (Player Settings > iOS > Target minimum iOS Version). " +
                    "Raise it there, or downgrade that dependency.");
            }

            throw new BuildFailedException($"{Tag} pod install failed (not a version conflict I can fix):\n{Tail(output, 60)}");
        }

        throw new BuildFailedException($"{Tag} Gave up after {MaxAttempts} passes. Fixes tried:\n  - " +
                                       string.Join("\n  - ", fixes));
    }

    // ------------------------------------------------------------------ Podfile edit

    /// <summary>Sets (or with empty version, removes) the version on `pod 'Name', 'ver', ...` lines.</summary>
    private static void SetPodVersion(string podfilePath, string pod, string version, string reason)
    {
        string podfile = File.ReadAllText(podfilePath);
        var regex = new Regex(
            @"^(?<head>\s*pod\s+'" + Regex.Escape(pod) + @"')(?<ver>\s*,\s*'[^']*')?(?<tail>.*)$",
            RegexOptions.Multiline);

        if (!regex.IsMatch(podfile))
        {
            Debug.LogWarning($"{Tag} Pod '{pod}' not in Podfile; {reason} ignored.");
            return;
        }

        version = (version ?? string.Empty).Trim();
        string patched = regex.Replace(podfile, m =>
        {
            string line = m.Groups["head"].Value + (version.Length == 0 ? "" : $", '{version}'") + m.Groups["tail"].Value;
            Debug.Log($"{Tag} ({reason}) {m.Value.Trim()}  ->  {line.Trim()}");
            return line;
        });

        File.WriteAllText(podfilePath, patched);
    }

    // ------------------------------------------------------------------ source lookup

    private static Dictionary<string, List<string>> _podSources;

    /// <summary>Which *Dependencies.xml files declare this pod (for the report).</summary>
    private static string DescribeSources(string pod)
    {
        if (_podSources == null)
        {
            _podSources = new Dictionary<string, List<string>>();
            foreach (string guid in AssetDatabase.FindAssets("Dependencies"))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!path.EndsWith("Dependencies.xml", StringComparison.OrdinalIgnoreCase))
                    continue;
                try
                {
                    foreach (XElement e in XDocument.Load(path).Descendants("iosPod"))
                    {
                        string name = (string)e.Attribute("name");
                        if (string.IsNullOrEmpty(name)) continue;
                        if (!_podSources.TryGetValue(name, out var list))
                            _podSources[name] = list = new List<string>();
                        list.Add($"{path} [{(string)e.Attribute("version") ?? "any"}]");
                    }
                }
                catch (Exception ex)
                {
                    Debug.LogWarning($"{Tag} Could not parse {path}: {ex.Message}");
                }
            }
        }

        return _podSources.TryGetValue(pod, out var sources) ? string.Join("; ", sources) : "unknown XML";
    }

    // ------------------------------------------------------------------ conflict parsing

    private class PodRequirement
    {
        public string Requirement; // e.g. "= 13.10.0"
        public string Via;         // root pod that pulled it in, e.g. "AppLovinMediationGoogleAdapter (= 13.10.0.0)"
    }

    private class PodConflict
    {
        public string Pod;
        public readonly List<string> Direct = new List<string>();
        public readonly List<PodRequirement> Transitive = new List<PodRequirement>();
        public bool FromLockfile;
        private string _raw;

        // [!] CocoaPods could not find compatible versions for pod "X":
        //   In Podfile:
        //     A (= 1.0) was resolved to 1.0, which depends on
        //       X (= 13.10.0)
        //
        //     X (~> 11.13.0)
        public static PodConflict Parse(string output)
        {
            Match header = Regex.Match(output, "could not find compatible versions for pod \"(?<pod>[^\"]+)\":");
            if (!header.Success)
                return null;

            var c = new PodConflict { Pod = header.Groups["pod"].Value };
            var reqLine = new Regex(@"^\s*" + Regex.Escape(c.Pod) + @" \((?<req>.+)\)\s*$");
            var chainStart = new Regex(@"^\s*(?<root>\S+ \([^)]*\)).*which depends on\s*$");

            var block = new StringBuilder();
            string section = "";
            string prev = "";
            string root = null;

            string rest = output.Substring(header.Index + header.Length);
            foreach (string raw in rest.Split('\n').Skip(1))
            {
                string line = raw.TrimEnd('\r');
                if (line.Trim().Length == 0) continue;
                if (!char.IsWhiteSpace(line[0])) break; // end of the indented conflict block
                block.AppendLine(line);

                string t = line.Trim();
                if (t.StartsWith("In ") && t.EndsWith(":"))
                {
                    section = t;
                    prev = t;
                    root = null;
                    continue;
                }

                bool lockSection = section.Contains("snapshot") || section.Contains("Podfile.lock");

                Match chain = chainStart.Match(line);
                if (chain.Success && !prev.EndsWith("which depends on"))
                    root = chain.Groups["root"].Value;

                Match rm = reqLine.Match(line);
                if (rm.Success)
                {
                    if (lockSection) c.FromLockfile = true;
                    else if (prev.EndsWith("which depends on"))
                        c.Transitive.Add(new PodRequirement { Requirement = rm.Groups["req"].Value, Via = root ?? "?" });
                    else
                        c.Direct.Add(rm.Groups["req"].Value);
                }

                prev = t;
            }

            c._raw = block.ToString();
            return c;
        }

        public string Describe(bool pinned)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"{Tag} Unresolvable CocoaPods conflict for '{Pod}'.");
            if (pinned)
                sb.AppendLine($"  '{Pod}' is pinned in {ConfigPath}; the auto-resolver won't change it.");
            foreach (string d in Direct)
                sb.AppendLine($"  Podfile wants {Pod} ({d}) - declared in {DescribeSources(Pod)}");
            foreach (PodRequirement r in Transitive)
            {
                string rootName = r.Via.Split(' ')[0];
                sb.AppendLine($"  {r.Via} wants {Pod} ({r.Requirement}) - declared in {DescribeSources(rootName)}");
            }
            if (Transitive.Select(t => t.Requirement).Distinct().Count() > 1)
                sb.AppendLine("  Several pods need different versions: align their plugin/adapter versions.");
            sb.AppendLine("CocoaPods output:");
            sb.Append(_raw);
            return sb.ToString();
        }
    }

    // ------------------------------------------------------------------ process

    private static string _podPath;

    /// <summary>
    /// Finds the `pod` binary. Unity launched from CI or the Hub doesn't get the user's zsh PATH,
    /// so check POD_PATH, the usual Homebrew/gem locations, then ask a zsh login shell.
    /// </summary>
    private static string FindPod()
    {
        if (_podPath != null) return _podPath;

        string home = Environment.GetEnvironmentVariable("HOME") ?? "";
        var candidates = new List<string>
        {
            Environment.GetEnvironmentVariable("POD_PATH"),
            "/opt/homebrew/bin/pod",
            "/usr/local/bin/pod",
            Path.Combine(home, ".gem/bin/pod"),
            "/usr/bin/pod",
        };
        foreach (string c in candidates)
        {
            if (!string.IsNullOrEmpty(c) && File.Exists(c))
                return _podPath = c;
        }

        try
        {
            var psi = new ProcessStartInfo("/bin/zsh", "-lc \"command -v pod\"")
            {
                UseShellExecute = false, RedirectStandardOutput = true, CreateNoWindow = true,
            };
            using (var p = Process.Start(psi))
            {
                string found = p.StandardOutput.ReadToEnd().Trim();
                p.WaitForExit();
                if (p.ExitCode == 0 && File.Exists(found))
                    return _podPath = found;
            }
        }
        catch { /* fall through */ }

        throw new BuildFailedException(
            $"{Tag} CocoaPods ('pod') not found. Install it (brew install cocoapods) or set POD_PATH.");
    }

    private static (int exitCode, string output) RunPod(string workingDir, string args)
    {
        string pod = FindPod();
        var psi = new ProcessStartInfo(pod, args)
        {
            WorkingDirectory = workingDir,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
        };
        // CocoaPods refuses to run without a UTF-8 locale.
        psi.EnvironmentVariables["LANG"] = "en_US.UTF-8";
        psi.EnvironmentVariables["LC_ALL"] = "en_US.UTF-8";
        psi.EnvironmentVariables["COCOAPODS_DISABLE_STATS"] = "true";
        // pod is a Ruby script; make sure its own bin dir (and Homebrew's) is on PATH for ruby/git.
        string path = psi.EnvironmentVariables["PATH"] ?? "";
        psi.EnvironmentVariables["PATH"] =
            $"{Path.GetDirectoryName(pod)}:/opt/homebrew/bin:/usr/local/bin:{path}";

        var output = new StringBuilder();
        using (var p = new Process { StartInfo = psi })
        {
            p.OutputDataReceived += (_, e) => { if (e.Data != null) lock (output) output.AppendLine(e.Data); };
            p.ErrorDataReceived += (_, e) => { if (e.Data != null) lock (output) output.AppendLine(e.Data); };

            try { p.Start(); }
            catch (Exception e) { throw new BuildFailedException($"{Tag} Could not start CocoaPods: {e.Message}"); }

            p.BeginOutputReadLine();
            p.BeginErrorReadLine();

            if (!p.WaitForExit(PodTimeoutMinutes * 60 * 1000))
            {
                try { p.Kill(); } catch { /* already gone */ }
                throw new BuildFailedException($"{Tag} pod {args} timed out after {PodTimeoutMinutes} min.");
            }
            p.WaitForExit(); // flush async readers

            lock (output) return (p.ExitCode, output.ToString());
        }
    }

    private static string Tail(string text, int lines)
    {
        string[] all = text.Split('\n');
        return string.Join("\n", all.Skip(Math.Max(0, all.Length - lines)));
    }
}
#endif
